belarusianin/belarusianin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from app_blrs.views import index, test_db
from catalog.views import list_products, render_product_page
from cart.views import add_to_cart, remove_from_cart, cart_detail, update_quantity
from orders.views import create_order
from feedback.views import manage_feedback, manage_contacts


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tested/', test_db, {'title': 'This is title!', 'secstr': 'Second string'}),
    url(r'^$', index, name='index'),
    url(r'^catalog/', include('catalog.urls', namespace='catalog')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^news/', include('news.urls')),
    url(r'^feedback/', manage_feedback, name='feedback'),
    url(r'^contacts/', manage_contacts, name='contacts'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^blockonomics/', include('blockonomics.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

belarusianin/cart/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='open_cart'),
    url(r'^add/(?P<product_id>[-\d]*)/$', views.add_to_cart, name='add'),
    url(r'^remove/(?P<product_id>[-\d]+)/$', views.remove_from_cart, name='remove'),
    url(r'^update/$', views.update_quantity, name='update_quantity'),
]

belarusianin/catalog/urls.py
from django.conf.urls import url

from . import views


#app_name = 'catalog'
urlpatterns = [
    url(r'^$', views.list_products, name='list_all_products'),
    url(r'^(?P<category_slug>[-\w]*)/$', views.list_products, name='list_products_by_category'),
    url(r'^(?P<category_slug>[-\w]+)/(?P<id>\d+)-(?P<product_slug>[-\w]+)/$',
        views.render_product_page, name='render_product')
]

belarusianin/catalog/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Category(models.Model):
    name = models.CharField(max_length=80, verbose_name='Название категории')
    slug = models.SlugField(max_length=200, db_index=True)
    description = models.CharField(max_length=200, verbose_name='Краткое описание')
    image = models.ImageField(upload_to='catalog/categories_images/', blank=True, verbose_name='Изображение категории')

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('catalog:list_products', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', verbose_name='Категория')
    name = models.CharField(max_length=200, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='catalog/products_images/%Y/%m/%d/', blank=True, verbose_name='Изображение товара')
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    stock = models.PositiveIntegerField(verbose_name='На складе')
    available = models.BooleanField(default=True, verbose_name='Доступен')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = [
            ['id', 'slug']
        ]

    def get_absolute_url(self):
        return reverse('catalog:render_product', kwargs={'id': self.id,
                                                         'product_slug': self.slug,
                                                         'category_slug': self.category.slug})

    def __str__(self):
        return '{}/{}'.format(self.category, self.name)


class ProductAttribute(models.Model):
    product = models.ForeignKey(Product, related_name='attributes', db_index=True, verbose_name='Товар')
    attribute_name = models.CharField(max_length=80, db_index=True, verbose_name='Название характеристики')
    attribute_value = models.CharField(max_length=200, verbose_name='Значение характеристики')

    class Meta:
        verbose_name = 'Характеристика товара'
        verbose_name_plural = 'Характеристики Товаров'

    def __str__(self):
        return '{}-{}-{}'.format(self.product, self.attribute_name, self.attribute_value)

belarusianin/catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product, ProductAttribute
from cart.forms import CartAddProductForm


def list_products(request, category_slug=None):
    if category_slug:
        current_category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=current_category)
    else:
        current_category = None
        products = Product.objects.all()
    return render(request, 'catalog/list.html', {
                  'category': current_category,
                  'products': products
    })


def render_product_page(request, id, product_slug, category_slug):
    print('Page opened!')
    current_category = get_object_or_404(Category, slug=category_slug)
    current_product = get_object_or_404(Product, id=id, slug=product_slug, category=current_category)
    add_to_cart_form = CartAddProductForm()
    return render(request, 'catalog/product_page.html',
                  {'product': current_product,
                   'cart_form': add_to_cart_form
                   })

belarusianin/catalog/templates/catalog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <style>
      body {
       background-color:silver;
       color:black;
       margin:0;
       background-image:url(media/background/mars.jpg);
       background-attachment:fixed;
      }
  </style>
  <!-- Styles -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
  <div class="navbar-default" role="navigation">
        <nav class="navbar navbar-default">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Навигация</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/"><img src="../media/catalog/logo.jpg"></a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
				<li><a href="/">Главная</a></li>
                <li><a href="{% url 'catalog:list_all_products' %}">Каталог</a></li>
                <li><a href="{% url 'contacts' %}">Контакты</a></li>
                  {% if cart|length > 0 %}
                    <li><a href="{% url 'cart:open_cart' %}">В корзине {{cart|length}} на сумму {{cart.get_total_price }}</a></li>
                  {% else %}
                    <li ><a href="{% url 'cart:open_cart' %}">В корзине пусто</a></li>
                  {% endif %}
                <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
                {% if user.is_authenticated %}
                <li><a href="/accounts/{{user}}/">Привет, {{user}}</a></li>
                <li><a href="{% url 'userena_signout' %}">Выйти</a></li>
                  {% else %}
                <li><a href="{% url 'userena_signin' %}">Войти</a></li>
                <li><a href="{% url 'userena_signup' %}">Зарегистрироваться</a></li>
                  {% endif %}
              </ul>
            </div>
          </div>
        </nav> 
      </div>
  <section id="content row" class="container">
    {% block content %}
    {% endblock %}
    {% block content2 %}
    {% endblock %}
  </section>
</body>
</html>

belarusianin/catalog/templates/catalog/list.html
{% extends 'catalog/base.html' %}

{% load static %}

{% block title %}
  {% if category %} {{ category.name }} {% else %} Страница товаров {% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar" class="col-sm-3">
    <h3>Категории</h3>
    <ul>
      <li {% if not category %} class="selected" {% endif %}>
        <a href=" ">Все</a>
      </li>
      {% for cat in categories %}
        <li {% if category.slug == cat.slug %} class="selected" {% endif %}>
          <a href=" ">{{ cat.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product_list col-sm-9">
    <h1>{% if category %}{{ category.name }}{% else %}Товары{% endif %}</h1>
    <div class="items row">
      {% for product in products %}
        <div class="item col-sm-4">
          <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}" class="img-responsive">
          </a>
          <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
          {{ product.price }} MRC.
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

belarusianin/catalog/templates/catalog/product_page.html
{% extends 'catalog/base.html' %}

{% load static %}

{% block title %}
  {% if category %} {{ category.name }} {% else %} Страница товаров {% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar" class="col-sm-3">
    <h3>Категории</h3>
    <ul>
      <li {% if not category %} class="selected" {% endif %}>
        <a href=" ">Все</a>
      </li>
      {% for cat in categories %}
        <li {% if category.slug == cat.slug %} class="selected" {% endif %}>
          <a href=" ">{{ cat.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product_list col-sm-9">
    <h1>{{ product.name }}</h1> <h2>{{ product.price }} руб.</h2>
    <div class="items row">
      
        <div class="item col-sm-12">
          
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}" class="img-responsive">
          <h4>Описание: {{ product.description }}</h4>
          <h4>Осталось на складе: {{ product.stock }}</h4>
    <form action="{% url "cart:add" product.id %}" method="post">
        {{ cart_form }}
        {% csrf_token %}
        <input type="submit" value="Добавить в корзину">
    </form>
          
          
        </div>
    </div>
  </div>
{% endblock %}