belarusianin/belarusianin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from app_blrs.views import index, test_db
from catalog.views import list_products, render_product_page
from cart.views import add_to_cart, remove_from_cart, cart_detail, update_quantity
from orders.views import create_order
from feedback.views import manage_feedback, manage_contacts


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tested/', test_db, {'title': 'This is title!', 'secstr': 'Second string'}),
    url(r'^$', index, name='index'),
    url(r'^catalog/', include('catalog.urls', namespace='catalog')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^news/', include('news.urls')),
    url(r'^feedback/', manage_feedback, name='feedback'),
    url(r'^contacts/', manage_contacts, name='contacts'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^blockonomics/', include('blockonomics.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

belarusianin/cart/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='open_cart'),
    url(r'^add/(?P<product_id>[-\d]*)/$', views.add_to_cart, name='add'),
    url(r'^remove/(?P<product_id>[-\d]+)/$', views.remove_from_cart, name='remove'),
    url(r'^update/$', views.update_quantity, name='update_quantity'),
]

belarusianin/catalog/urls.py
from django.conf.urls import url

from . import views


#app_name = 'catalog'
urlpatterns = [
    url(r'^$', views.list_products, name='list_all_products'),
    url(r'^(?P<category_slug>[-\w]*)/$', views.list_products, name='list_products_by_category'),
    url(r'^(?P<category_slug>[-\w]+)/(?P<id>\d+)-(?P<product_slug>[-\w]+)/$',
        views.render_product_page, name='render_product')
]

belarusianin/orders/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^create/$', views.create_order, name='create_order')
]

belarusianin/cart/models.py
from django.db import models

# Create your models here.

belarusianin/cart/forms.py
from django import forms



PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)


#class CartQuantityProduct(forms.Form):
#    quantity = forms.IntegerField(min_value=0, step=1)

belarusianin/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from catalog.models import Product
from .session_cart import Cart
from .forms import CartAddProductForm
#from cart.forms import CartQuantityProduct


@require_POST
def add_to_cart(request, product_id):
    cart = Cart(request)
    #product = get_object_or_404(Product, product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cleaned_data = form.cleaned_data
        cart.add_product(product_id=product_id,
                         quantity=cleaned_data['quantity'])
    return redirect('cart:open_cart')


#@require_POST
def remove_from_cart(request, product_id):
    cart = Cart(request)
    #product = get_object_or_404(Product, id=product_id)
    cart.remove_product_from_cart(product_id)
    return redirect('cart:open_cart')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})


@require_POST
def update_quantity(request):
    cart = Cart(request)
    for key in request.POST:
        if key not in ('csrfmiddlewaretoken', 'submit'):
            cart.add_product(product_id=key,
                             quantity=int(request.POST[key]))
    return redirect('cart:open_cart')

belarusianin/cart/templates/cart/detail.html
{% extends "catalog/base.html" %}

{% block title %}
  Ваша корзина товаров
{% endblock %}

{% block content %}
  <h1>Ваша корзина товаров</h1>
    <form action="{% url 'cart:update_quantity' %}" method="post">
      <table class="table">
        <thead>
          <tr>
            <th>Изображение</th>
            <th>Продукт</th>
            <th>Количество</th>
            <th>Цена</th>
            <th>Полная цена</th>
              <th>Удалить</th>
          </tr>
        </thead>
        <tbody>
          {% for item in cart %}
            {% with product=item.product %}
              <tr>
                <td>
                  <a href="{{ product.get_absolute_url }}">
                    <img src="{{ product.image.url }}" alt="no_image" style="max-height: 100px;">
                  </a>
                </td>
                <td>{{ product.name }}</td>
                <td><input name="{{ product.id }}" type="number" step="1" min="0" max="" value="{{ item.quantity }}" title="Кол-во" size="1" pattern="[0-9]*" inputmode="numeric" class="form-control" style="max-width: 70px;"></td>
                
                <td class="num">{{ item.price }} руб.</td>
                <td class="num">{{ item.total_price }} руб.</td>
                  <td><a href="{% url 'cart:remove' product.id %}">Удалить</a></td>
              </tr>
            {% endwith %}
          {% endfor %}
            {% csrf_token %}
            <tr class="total">
              
              <td colspan="2"></td>
                <td><input name="submit" type="submit" value="Обновить"></td>
                <td>Total</td>
              <td class="num">{{ cart.get_total_price }} руб.</td>
            </tr>
        </tbody>
      </table>
        
</form>
  <p class="text-right">
    <a href="{% url "catalog:list_all_products"%}" class="btn">Продолжить Шопинг</a>
    <a href="{% url "orders:create_order" %}">Оформить заказ</a>
  </p>
{% endblock %}